spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://b92d99315a66da:0ed1b4dd@us-cdbr-iron-east-05.cleardb.net/heroku_6878de95a3b2d0d?reconnect=true
  jpa:
    database: MYSQL
    hibernate:
      ddl-auto: update
    show-sql: false
    #database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        dialect.storage_engine: innodb



server:
  port: 8081
